### ISSUE TITLE
Hoe je Hello World aanmaakt is niet nodig

### ISSUE THREAD

**Issue by ManoukK** [kimgarrard/frontend-applications#1]
In je readme beschrijf je hoe je een hello world aan kan maken. Dit is niet nodig omdat het de bedoeling is dat anderen jou bestand gaan clonen en gebruiken. Dit kan je eruit laten

**Comment by kimgarrard** [comment]
Klopt, ik heb het nu aangepast naar hoe je dit project kan clonen.
